name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cancel_ci:
    name: Mandatory checks before CI
    runs-on: ubuntu-latest
    outputs:
      run_next: ${{ steps.skip_ci_step.outputs.run_next }}
    steps:
    - name: Check skip CI
      uses: OpenAstronomy/action-skip-ci@main
      id: skip_ci_step
      with:
        NO_FAIL: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # The rest only run if above are done

  pep_and_audit:
    runs-on: ubuntu-16.04
    needs: cancel_ci
    if: needs.cancel_ci.outputs.run_next == 'true'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch tags
      run: git fetch --prune --unshallow --tags
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Lint with flake8
      run: |
        python -m pip install --upgrade pip flake8
        flake8 --count
    # Make sure that packaging will work
    - name: pep517 build
      run: |
        python -m pip install --upgrade setuptools build twine
        python -m build --sdist .
        twine check dist/*
    - name: Security audit
      run: |
        python -m pip install --upgrade bandit
        bandit -r . -c .bandit.yaml

  # Python 3.7 + Numpy 1.19 resulted in NaN results, so we downgrade Numpy.
  initial_tests:
    runs-on: ubuntu-16.04
    needs: cancel_ci
    if: needs.cancel_ci.outputs.run_next == 'true'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch tags
      run: git fetch --prune --unshallow --tags
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install and build
      run: |
        sudo apt-get install libxml2-utils
        python -m pip install --upgrade pip setuptools
        python -m pip install 'numpy<1.19'
        python -m pip install -e .[test,all]
    - name: Test with stable deps and coverage
      run: pytest --cov=./ --cov-report=xml --remote-data
    - name: Coverage report
      uses: codecov/codecov-action@v1

  dev_deps_tests:
    runs-on: ubuntu-latest
    needs: cancel_ci
    if: needs.cancel_ci.outputs.run_next == 'true'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch tags
      run: git fetch --prune --unshallow --tags
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install and build
      run: |
        sudo apt-get install libxml2-utils
        python -m pip install --upgrade pip setuptools
        python -m pip install git+https://github.com/astropy/astropy.git@master#egg=astropy
        python -m pip install -e .[test,all]
    - name: Test with dev deps
      run: pytest --remote-data
